version: '3.9'

services:
  bot_core:
    network_mode: host  # Используем сеть хоста для прямого доступа
    container_name: bot_core_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      TZ: Europe/Moscow
    volumes:
      - .:/brusnika_bot
    restart: unless-stopped
    cap_add:  # Даем необходимые привилегии
      - NET_ADMIN
      - SYS_ADMIN

# Явно не определяем networks, так как используем network_mode: host