# Generated by Django 5.1.5 on 2025-01-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_core', '0002_userprofile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
    ]
